### ISSUE TITLE
Move blog.redash.io from Medium to Ghost

### ISSUE THREAD

**Issue by arikfr** [getredash/blog-theme#1]
I wanted to move our blog for a long time of Medium. The options were either host it with [Ghost](https://ghost.org) or just implement as part of our websites.

Both options have their pros and cons, but considering this is not very high priority I figured that going with Ghost is the shortest path to success. There is a tool to import Medium posts into Ghost, which I already used. The result is here: https://redash.ghost.io/ (it's password protected to keep away the search engines, use `redash` as password).

There are still a few things to do:

- [x] Make the header design more consistent with out website and less dark
- [ ] Google Analytics
- [ ] Make sure all URLs are the same as they were or have redirects setup
- [ ] Manually migrate posts not written by me (the tool exports what I wrote)
  - [ ] Manually migrate [Danya’s blog post](https://blog.redash.io/alooma-redash-for-pros-dashboads-etl-307dc189d3a5)
  - [ ] Manually migrate [Zsolt's blog post](https://blog.redash.io/improving-redash-user-experience-36e3ca47d1b3)
- [ ] Decide on a name (currently named it "Inside Redash")
- [ ] Setup domain name (blog.redash.io) to point at new blog (and remove password)
- [ ] Tell Medium to stop using cname 

NTH:
- [ ] Setup link to Discourse for discussions (instead of comments)
- [ ] Zapier Zap to subscribe Ghost subscribers to our newsletter
- [ ] Write a blog post about the migration

**Comment by ranbena** [comment]
> Worth having some hover effect in nav-bar.

Of course it's on the list.

> Let's remove the featured image from blog posts.

I think it would be better to remove the images from post's content.

> Something about the images hitting the border here feels wrong.

To me too. I'll pad it.

> Now that the subscribe block has non white background, maybe it should come below the "author block"? The other option is to remove the author block and show the author name/avatar at the top below the title. Considering the nature of our blog, I guess it makes more sense.

I gave no attention to content presentation yet. I'll play around with it.

**Comment by arikfr** [comment]
> I think it would be better to remove the images from post's content.

Why? It's nice to have them in the list view, but they serve no purpose (and currently look bad) in the post itself.

**Comment by ranbena** [comment]
@arikfr I finalized work on my local ghost installation.
Need to upload and test on https://redash.ghost.io (which is currently offline).
